#!/usr/bin/env bash
set -euo pipefail

BASE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TASKS_DIR="$BASE_DIR/tasks/incoming"
PLAN_SCRIPT="$BASE_DIR/scripts/plan-task.sh"

if [[ $# -lt 1 ]]; then
  echo "Uso:"
  echo "  ./scripts/ai-task.sh \"descrição da tarefa\""
  exit 1
fi

TASK_TEXT="$*"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
TASK_FILE="$TASKS_DIR/task-$TIMESTAMP.md"

mkdir -p "$TASKS_DIR"

# Cria base da task
cat > "$TASK_FILE" <<TASK
# AI Task

## Request
$TASK_TEXT

## Status
NEW

## Auto Analysis
(Pending)

## Suggested Plan
(Pending)

## Notes
Generated by ai-task.sh
TASK

echo "Tarefa criada:"
echo "  $TASK_FILE"
echo ""

# Gera plano automaticamente
if [[ -x "$PLAN_SCRIPT" ]]; then
  PLAN_OUTPUT="$($PLAN_SCRIPT "$TASK_TEXT")"

  # Atualiza o arquivo da task com o plano
  awk -v plan="$PLAN_OUTPUT" '
    /## Auto Analysis/ {
      print;
      print "";
      print "```";
      print plan;
      print "```";
      next
    }
    { print }
  ' "$TASK_FILE" > "$TASK_FILE.tmp"

  mv "$TASK_FILE.tmp" "$TASK_FILE"

  echo "Plano gerado automaticamente."
else
  echo "Aviso: plan-task.sh não encontrado ou não executável."
fi

echo ""
echo "Próximo passo:"
echo "  Revisar plano antes de executar qualquer ação"
