#!/usr/bin/env bash
set -euo pipefail

BASE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TASKS_DIR="$BASE_DIR/tasks/incoming"

if [[ $# -lt 1 ]]; then
  echo "Uso:"
  echo "  ./scripts/ai-task.sh \"descrição da tarefa\""
  exit 1
fi

TASK_TEXT="$*"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
TASK_FILE="$TASKS_DIR/task-$TIMESTAMP.md"

cat > "$TASK_FILE" <<TASK
# AI Task

## Request
$TASK_TEXT

## Status
NEW

## Suggested Flow
1. Manager receives task
2. Intake Agent structures task
3. Architect Agent selects spec
4. Analysis Agent evaluates risk
5. Execution Agent prepares changes
6. Review Agent validates
7. Documentation Agent records
8. Notification Agent reports pending approval

## Notes
This task was auto-generated by ai-task.sh
TASK

echo "Tarefa registrada em: $TASK_FILE"
