#!/usr/bin/env bash
set -euo pipefail

BASE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TASKS_DIR="$BASE_DIR/tasks/incoming"

if [[ $# -lt 1 ]]; then
  echo "Uso:"
  echo "  ./scripts/ai-task.sh \"descrição da tarefa\""
  exit 1
fi

TASK_TEXT="$*"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
TASK_FILE="$TASKS_DIR/task-$TIMESTAMP.md"

cat > "$TASK_FILE" <<TASK
# AI Task

## Request
$TASK_TEXT

## Status
NEW

## Suggested Flow
1. Manager receives task
2. Spec Agent selects or creates spec
3. Architect Agent defines structure
4. Executor Agent applies changes
5. Reviewer Agent validates
6. Documentation Agent updates docs

## Suggested Specs
- observability standardization
- service onboarding
- platform governance

## Notes
This file is auto-generated by ai-task.sh
TASK

echo "Tarefa registrada em:"
echo "  $TASK_FILE"
echo ""
echo "Próximo passo sugerido:"
echo "  - Verificar qual spec se aplica"
echo "  - Executar workflow correspondente"
